# fly.toml app configuration file generated for nikita-base-test-3 on 2023-08-31T14:10:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nikita-base-test-3"
primary_region = "yul"

[env]
  PORT = "8081"
  HOST = "https://nikita-base-test-3.fly.dev"
  SHOPIFY_API_KEY = "5e693aba73bf47d63073968907cfa137"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
